### PR TITLE
Split maintenance response creation

### PR DESCRIPTION
**Pull request by ziima**
Preparation for #23 - split function to create a maintenance response.

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
Thanks for this PR.
The redirect check is present twice, in the middleware and in the `get_maintenance_response`.
This made me think that the best solution is to move the `process_request` method of the middlewareto the core module.

**Comment by ziima** [comment]
No sure what do you mean by redirect check. The `get_maintenance_response` should only create the response, not decide whether it should be returned. I intent to move that part of middleware in another PR.

**Comment by ziima** [comment]
I rebased the change. Is there anything blocking the merge?

**Comment by fabiocaccamo** [comment]
Hi @ziima, could you move the get_maintenance_response method from the core module to a new http module?!

**Comment by ziima** [comment]
Moved.

**Comment by fabiocaccamo** [comment]
Thanks!

**Pull request merged**
