### PR TITLE
Add a new setting to specify a custom client IP getter method

### PR DESCRIPTION
**Pull request by frankie567**
Hi,

Thank you for this very good module!

Here is a pull request that may be useful for some developers out there who wants like me to filter against client IP but with a Django behind a load balancer or Docker network (in my case, have to check the `HTTP_X_FORWARDED_FOR` header):

Introduce a **new setting** `MAINTENANCE_MODE_IP_GETTER_METHOD` which is a **path to a method that returns an IP** given the `request` object. The default methods returns, as currently, `request.META['REMOTE_ADDR']`.

Hope it'll be useful and you'll consider merging to main repository 😃 

Regards,

François Voron

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
@frankie567 thank you for the good idea and pull request.
I would ask you just this change: when I read the setting name for the first time, it was not clear to me, so I would rename it to `MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS`

Do you think that could be a good idea to get client ipaddress using https://github.com/un33k/django-ipware by default?

**Comment by frankie567** [comment]
I changed the setting name :)

Concerning `django-ipware`, it seems quite nice and complete! However, it would add a dependency that may not be interesting for developers who don't want to filter on IP address. Don't know if it could be an issue.

If you wish, I could look into implementing it :)

**Comment by fabiocaccamo** [comment]
You're right about `django-ipware`, I will just suggest it in the README.
Thanks

**Comment by gthieleb** [comment]
Thanks for this useful contribution! 
Would you mind mentioning the use of `ipware` in the documentation? 
I can confirm that this setting and ipware works together like a charm.

    MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS = 'ipware.ip.get_ip'

**Comment by fabiocaccamo** [comment]
@gthieleb thanks for the reminder. I added a note about `ipware` in the settings section.

**Pull request merged**
