### PR TITLE
Leave django admin open - settings flag

### PR DESCRIPTION
**Pull request by GitRon**
Added new settings flag to be able to leave the django admin open while shutting down the rest of the site.

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
@GitRon thanks for this PR, this feature was already on my todo...

I would just rename the setting name `MAINTENANCE_MODE_IGNORE_ADMIN_SITES` to `MAINTENANCE_MODE_IGNORE_ADMIN_SITE` (without trailing 's'), I think it is more correct.

By the way, as you can see test have failed, you should add admin to settings and urls too.

**Comment by GitRon** [comment]
@fabiocaccamo I take care of the new variable name and the tests. Thanks for the feedback!

**Comment by fabiocaccamo** [comment]
@GitRon I mean that you should test this feature with both admin app installed and not. This is the reason of tests failure.

**Comment by GitRon** [comment]
@fabiocaccamo Yes, I know! Just found another problem I fixed. Any ideas how to test the admin installation?
BTW: In another package the contributor told me to use @override_settings()-decorator instead of manipulating the settings directly. You might want to consider this.

**Comment by GitRon** [comment]
@fabiocaccamo Any idea why now all the tests fail with this?

> django.template.exceptions.TemplateDoesNotExist: 503.html

Thx

**Comment by fabiocaccamo** [comment]
You should run tests locally, before pushing ;)
By the way, I did it myself, you can upgrade to `0.10.0` version.

**Pull request closed without merging**
