### PR TITLE
Fix missing import and TypeError in middleware

### PR DESCRIPTION
**Pull request by martinogden**

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
Hi @martinogden, 
some considerations about your PR:

1. if you don't use anymore the `get_request_context` method you should remove it from the middleware.
2. it seems that you are not passing anymore the `RequestContext`, please check this closed issue: https://github.com/fabiocaccamo/django-maintenance-mode/issues/3

For the moment I fix just the import error.
Thanks

**Comment by martinogden** [comment]
Hi @fabiocaccamo. I've added back in the request context. Also, the [`render`](https://docs.djangoproject.com/en/1.10/topics/http/shortcuts/#render) method requires the context as a `dict` rather than `RequestContext`.

Cheers

**Comment by fabiocaccamo** [comment]
Could you open a more detailed issue about the TypeError describing which Django version are you using, etc?

**Comment by fabiocaccamo** [comment]
Fixed with 0.4.1 version

**Pull request closed without merging**
